#!/usr/bin/python3
# -*- coding: utf-8 -*-

from random import randint

"""
    Eğlenceli bir çarpım tablosu uygulaması
"""

print("-" * 100)
print("\t\t                              HOŞGELDİNİZ..")
print("-" * 100, "\n")


def carpim(i, j, r):
    if r != "-1":
        result = str(i * j)
        if result == r:
            print("\t\t***** Bildin *****")
        else:
            print("\t!!! Bilemedin %s olacaktı" % result)
    else:

        secim()


def basla(rng_1, rng_2):
    if rng_1 > 10:
        x = 10
    else:
        x = 5
    for i in range(0, x):
        for j in range(0, x):
            sayi_1 = randint(rng_1, rng_2)
            sayi_2 = randint(rng_1, rng_2)
            print("_" * 50, "\n")
            print("\t%d x %d kaça eşittir? (Kappa = -1)" % (sayi_1, sayi_2))
            sonuc = input("sonuc >> ")
            carpim(sayi_1, sayi_2, sonuc)

            if i == 4 and j == 4:
                print("\n *-- Bu bölüm bitti bir üst bölüme geçebilsiniz --*\n")
                secim()


def secim():
    print(" Hangi seviyeden başlamak istiyorsunuz (çıkış = -1) ?\n")
    print("  1 - 1.sınıfdan mı başlıyoruz ? ")
    print("  2 - Hadi ama yaparsın ")
    print("  3 - Yani eh işte ")
    print("  4 - Dene ve gör\n")

    svy = input(" >> ")

    if svy == "1":
        basla(1, 16)

    elif svy == "2":
        basla(16, 122)

    elif svy == "3":
        basla(122, 215)

    elif svy == "4":
        basla(215, 2100)

    else:
        exit(0)


if __name__ == '__main__':
    secim()



